on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: .NET CI

jobs:
  test:
    name: Test .NET SDK
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        rust:
          - stable
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

# Install libextism
## linux
      - name: Download Linux binaries
        if: runner.os == 'Linux'
        uses: robinraju/release-downloader@v1.8
        with:
          repository: 'extism/extism'
          tag: latest
          fileName: 'libextism-x86_64-unknown-linux-gnu-main.tar.gz'
          out-file-path: 'native'
          extract: true

      - name: Move Linux binaries to lib
        if: runner.os == 'Linux'
        run: |
          sudo mv native/extism.h /usr/local/include/
          sudo mv native/libextism.so  /usr/local/lib/

## macOS
      - name: Download macOS binaries
        if: runner.os == 'macOS'
        uses: robinraju/release-downloader@v1.8
        with:
          repository: 'extism/extism'
          tag: latest
          fileName: 'libextism-x86_64-apple-darwin-main.tar.gz'
          out-file-path: 'native'
          extract: true

      - name: Move macOS binaries to lib
        if: runner.os == 'macOS'
        run: |
          sudo mv native/extism.h /usr/local/include/
          sudo mv native/libextism.dylib  /usr/local/lib/

## Windows
      - name: Download Windows binaries
        if: runner.os == 'Windows'
        uses: robinraju/release-downloader@v1.8
        with:
          repository: 'extism/extism'
          tag: latest
          fileName: 'libextism-x86_64-pc-windows-msvc-main.tar.gz'
          out-file-path: 'test/Extism.Sdk/bin/Debug/net7.0'
          extract: true
          
      - name: Delete Native binary from nuget package
        if: runner.os == 'Windows'
        run: |
          Get-ChildItem -Recurse test/Extism.Sdk/bin/Debug/net7.0

# Setup .NET and run tests
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
           dotnet-version: 7.x

      - name: Test .NET Sdk
        if: runner.os == 'Windows'
        run: |
          make build
          Get-ChildItem -Recurse test/Extism.Sdk/bin/Debug/net7.0
          rm test/Extism.Sdk/bin/Debug/net7.0/runtimes/win-x64/native/Extism.dll

      - name: Test .NET Sdk
        run: |
          make test
