on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: .NET CI

jobs:
  test:
    name: Test .NET SDK
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x

      - name: Run tests
        run: |
          make test
