on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: .NET CI

jobs:
  test:
    name: Test .NET SDK
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      # macOS and Linux
      - name: Install libextism
        if: runner.os != 'Windows'
        uses: ./.github/actions/libextism

      # Windows
      - name: Download Windows binaries
        if: runner.os == 'Windows'
        uses: robinraju/release-downloader@v1.8
        with:
          repository: 'extism/extism'
          tag: latest
          fileName: 'libextism-x86_64-pc-windows-msvc-main.tar.gz'
          out-file-path: 'test/Extism.Sdk/bin/Debug/net7.0'
          extract: true

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x

      - name: Run tests
        run: |
          make test
