on:
  push:
    tags:
      - 'v*'

name: Release .NET SDK

jobs:
  release-sdks:
    name: release-dotnet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install libextism
        if: runner.os != 'Windows'
        uses: ./.github/actions/libextism

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
           dotnet-version: 7.x

      - name: Test .NET Sdk
        run: |
          make test

      - name: Generate Docs
        run: |
          dotnet tool update -g docfx
          docfx ./docfx.json

      - name: Publish .NET Sdk
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          make publish

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_site
